// Extract advance widths from the bundled IBM Plex Sans fonts into src/js/metrics.js, so text can be measured
// (wrapping, legends, snapping) without a browser. Minimal TrueType reader: head, hhea, hmtx, cmap (format 4).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const FACES = [['Regular', 400], ['Medium', 500], ['SemiBold', 600], ['Bold', 700]];
// Latin-1 plus the punctuation that shows up in network drawings
const CHARS = [];
for (let c = 32; c < 127; c++) CHARS.push(c);
for (let c = 160; c < 256; c++) CHARS.push(c);
CHARS.push(0x2013, 0x2014, 0x2018, 0x2019, 0x201C, 0x201D, 0x2022, 0x2026, 0x20AC, 0x2190, 0x2191, 0x2192, 0x2193, 0x2194, 0x2212, 0x2713, 0x00B7);

function tables(buf) {
  const n = buf.readUInt16BE(4);
  const t = {};
  for (let i = 0; i < n; i++) {
    const o = 12 + i * 16;
    t[buf.toString('ascii', o, o + 4)] = buf.readUInt32BE(o + 8);
  }
  return t;
}

function cmap4(buf, off) {
  const n = buf.readUInt16BE(off + 2);
  for (let i = 0; i < n; i++) {
    const pid = buf.readUInt16BE(off + 4 + i * 8), eid = buf.readUInt16BE(off + 6 + i * 8);
    const so = off + buf.readUInt32BE(off + 8 + i * 8);
    if (buf.readUInt16BE(so) === 4 && (pid === 3 || pid === 0) && (eid === 1 || pid === 0)) {
      const segX2 = buf.readUInt16BE(so + 6), seg = segX2 / 2;
      const ends = so + 14, starts = ends + segX2 + 2, deltas = starts + segX2, ranges = deltas + segX2;
      return (code) => {
        for (let s = 0; s < seg; s++) {
          const end = buf.readUInt16BE(ends + s * 2);
          if (code > end) continue;
          const start = buf.readUInt16BE(starts + s * 2);
          if (code < start) return 0;
          const delta = buf.readInt16BE(deltas + s * 2), ro = buf.readUInt16BE(ranges + s * 2);
          if (!ro) return (code + delta) & 0xFFFF;
          const g = buf.readUInt16BE(ranges + s * 2 + ro + (code - start) * 2);
          return g ? (g + delta) & 0xFFFF : 0;
        }
        return 0;
      };
    }
  }
  throw new Error('no format 4 cmap');
}

const out = {};
let upm = 1000;
for (const [name, weight] of FACES) {
  const buf = fs.readFileSync(path.join(ROOT, 'src/fonts', `IBMPlexSans-${name}.ttf`));
  const t = tables(buf);
  upm = buf.readUInt16BE(t.head + 18);
  const nh = buf.readUInt16BE(t.hhea + 34);
  const glyph = cmap4(buf, t.cmap);
  const adv = (g) => buf.readUInt16BE(t.hmtx + Math.min(g, nh - 1) * 4);
  const w = {};
  for (const c of CHARS) { const g = glyph(c); if (g) w[c] = adv(g); }
  out[weight] = w;
}
const js = `// Generated by tools/make-metrics.mjs from the bundled IBM Plex Sans fonts. Do not edit.
// Advance widths in font units (unitsPerEm ${upm}) per weight, keyed by code point.
export const UPM = ${upm};
export const WIDTHS = ${JSON.stringify(out)};
`;
fs.writeFileSync(path.join(ROOT, 'src/js/metrics.js'), js);
console.log('metrics written', Object.keys(out[400]).length, 'chars, upm', upm);
